-- ============================================================
-- 17 Quiz vragen — één per speeldag WK 2026 poulfase
-- Correct antwoord zit er al in (wordt automatisch gecontroleerd)
-- ============================================================
INSERT INTO quiz_questions (question_date, match_reference, question, option_a, option_b, option_c, correct_option) VALUES

('2026-06-11', 'Mexico vs Zuid-Afrika',
 'Het WK 2026 wordt georganiseerd door 3 landen. In welke jaren organiseerde Mexico eerder al een WK?',
 'Alleen in 1970',
 'In 1970 én 1986',
 'In 1970, 1986 én 2002',
 'B'),

('2026-06-12', 'Canada vs Bosnië-Herzegovina',
 'Canada heeft 6 tijdzones. Als De Klok hier om middernacht slaat voor een Nederlands WK-doelpunt, hoe laat is het dan in Vancouver?',
 '15:00 uur',
 '17:00 uur',
 '21:00 uur',
 'A'),

('2026-06-13', 'Qatar vs Zwitserland',
 'Qatar organiseerde het WK 2022. Wie won die editie en maakte de wereld een beetje minder droog dan het gastland?',
 'Brazilië',
 'Argentinië',
 'Frank de Boer',
 'B'),

('2026-06-14', 'Nederland vs Japan',
 'Japan haalde in 2002 als co-gastland het verst ooit op een WK. Tot welke ronde kwamen ze?',
 'Kwartfinale',
 'Achtste finale',
 'Ze haalden de halve finale',
 'A'),

('2026-06-15', 'België vs Egypte',
 'De Belgische Gouden Generatie (Hazard, De Bruyne, Lukaku) haalde ooit de WK-halve finale. In welk jaar was dat?',
 '2014 in Brazilië',
 '2018 in Rusland',
 '2022 in Qatar',
 'B'),

('2026-06-16', 'Frankrijk vs Senegal',
 'In 2002 versloeg Senegal de titelhouder in de groepsfase met 1-0. Welk land was die titelhouder?',
 'Brazilië',
 'Duitsland',
 'Frankrijk',
 'C'),

('2026-06-17', 'Engeland vs Kroatië',
 'Engeland won in 1966 het WK. Als ze 2026 winnen, hoeveel jaar hebben ze dan gewacht op de volgende titel?',
 '58 jaar',
 '60 jaar',
 '64 jaar',
 'B'),

('2026-06-18', 'Oezbekistan vs Colombia',
 'Oezbekistan is een van de twee landen ter wereld die worden omringd door landen die ook geen zeekust hebben (dubbellandingsstaat). Welk Europees land deelt die bijzonderheid?',
 'Zwitserland',
 'Liechtenstein',
 'Luxemburg',
 'B'),

('2026-06-19', 'Verenigde Staten vs Australië',
 'Australië versloeg Japan in de WK-groepsfase van 2006 op dramatische wijze in de slotminuten. Wat was de eindstand?',
 '2-1',
 '3-1',
 '1-0',
 'B'),

('2026-06-20', 'Nederland vs Zweden',
 'Nederland bereikte drie keer de WK-finale maar won hem nooit. In welke jaren?',
 '1974, 1978 en 2010',
 '1974, 1994 en 2010',
 '1966, 1974 en 1978',
 'A'),

('2026-06-21', 'Spanje vs Saoedi-Arabië',
 'Spanje won het WK 2010 in Zuid-Afrika. Wie scoorde de beslissende goal in de finale tegen Nederland?',
 'David Villa',
 'Fernando Torres',
 'Andrés Iniesta',
 'C'),

('2026-06-22', 'Argentinië vs Oostenrijk',
 'Hoeveel Gouden Ballen (Ballon d''Or) heeft Lionel Messi gewonnen — evenveel als dat wij graag Klokjes drinken tijdens een WK?',
 '7',
 '8',
 '9',
 'B'),

('2026-06-23', 'Jordanië vs Algerije',
 'Nederland grenst aan maar 2 landen. Welke zijn dat?',
 'België en Duitsland',
 'België en Frankrijk',
 'Duitsland en Luxemburg',
 'A'),

('2026-06-25', 'Tunesië vs Nederland',
 'Wat is het officiële motto van de Klokhuis WK-poule 2026?',
 'Oranje boven, alles eronder!',
 'Winnen is Drinken, Drinken is Winnen',
 'De klok tikt, de punten tikken mee',
 'B'),

('2026-06-26', 'Noorwegen vs Frankrijk',
 'Noorwegen versloeg Brazilië op het WK 1998 met 2-1. Welke Noor scoorde de beroemde beslissende goal?',
 'Ole Gunnar Solskjær',
 'Tore André Flo',
 'Kjetil Rekdal',
 'C'),

('2026-06-27', 'Uruguay vs Spanje',
 'Uruguay organiseerde en won het allereerste WK in 1930. Hoeveel landen namen deel aan dat eerste WK?',
 '13',
 '16',
 '24',
 'A'),

('2026-06-28', 'Colombia vs Portugal',
 'Cristiano Ronaldo draagt rugnummer 7. Hoeveel keer won hij de Champions League — toevallig ook het aantal Klokjes dat je wilt als hij scoort?',
 '4',
 '5',
 '6',
 'B');
