-- ============================================================
-- Seed data — voer dit uit NA het schema
-- ============================================================

-- Spelers
INSERT INTO users (name) VALUES
  ('Grote Koen'),
  ('Kleine Coen'),
  ('Eva'),
  ('Tess'),
  ('Jaïro'),
  ('Elena'),
  ('Kadia');

-- 48 WK 2026 Landen
INSERT INTO countries (name, flag_emoji) VALUES
  ('Amerika',       '🇺🇸'),
  ('Mexico',        '🇲🇽'),
  ('Canada',        '🇨🇦'),
  ('Duitsland',     '🇩🇪'),
  ('Spanje',        '🇪🇸'),
  ('Frankrijk',     '🇫🇷'),
  ('Engeland',      '🏴󠁧󠁢󠁥󠁮󠁧󠁿'),
  ('Portugal',      '🇵🇹'),
  ('Nederland',     '🇳🇱'),
  ('België',        '🇧🇪'),
  ('Kroatië',       '🇭🇷'),
  ('Zwitserland',   '🇨🇭'),
  ('Denemarken',    '🇩🇰'),
  ('Polen',         '🇵🇱'),
  ('Oostenrijk',    '🇦🇹'),
  ('Servië',        '🇷🇸'),
  ('Hongarije',     '🇭🇺'),
  ('Turkije',       '🇹🇷'),
  ('Oekraïne',      '🇺🇦'),
  ('Brazilië',      '🇧🇷'),
  ('Argentinië',    '🇦🇷'),
  ('Uruguay',       '🇺🇾'),
  ('Colombia',      '🇨🇴'),
  ('Ecuador',       '🇪🇨'),
  ('Chili',         '🇨🇱'),
  ('Costa Rica',    '🇨🇷'),
  ('Panama',        '🇵🇦'),
  ('Honduras',      '🇭🇳'),
  ('Marokko',       '🇲🇦'),
  ('Senegal',       '🇸🇳'),
  ('Nigeria',       '🇳🇬'),
  ('Kameroen',      '🇨🇲'),
  ('Egypte',        '🇪🇬'),
  ('Algerije',      '🇩🇿'),
  ('Zuid-Afrika',   '🇿🇦'),
  ('Ghana',         '🇬🇭'),
  ('Ivoorkust',     '🇨🇮'),
  ('Japan',         '🇯🇵'),
  ('Zuid-Korea',    '🇰🇷'),
  ('Iran',          '🇮🇷'),
  ('Saoedi-Arabië', '🇸🇦'),
  ('Australië',     '🇦🇺'),
  ('Qatar',         '🇶🇦'),
  ('Irak',          '🇮🇶'),
  ('Jordanië',      '🇯🇴'),
  ('Nieuw-Zeeland', '🇳🇿'),
  ('Venezuela',     '🇻🇪'),
  ('Slovenië',      '🇸🇮');
